from pathlib import Path

# path
testbed_dir = str(Path(__file__).parent / "testbed")
result_dir = str(Path(__file__).parent / "results")

coco_dir = ...
vqav2_dir = ...
ok_vqa_dir = ...
karpathy_coco_caption_dir = ...
hateful_memes_dir = ...
flickr30k_dir = karpathy_coco_caption_dir
flickr30k_images_dir = ...
ocr_vqa_dir = ...
ocr_vqa_images_dir = ...

idefics_9b_path = ...
llava_interleave_7b_path = ...
idefics2_8b_path = ...
idefics2_8b_base_path = ...
